
name = "DashLeaflet"
uuid = "1b08a953-4be3-4667-9a23-b00d553a4565"
authors = ["Emil Haldrup Eriksen <emil.h.eriksen@gmail.com>"]
version = "0.1.3"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = ">=0.1"
